[package]
name = "speakersafetyd"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Speaker protection daemon for embedded Linux systems"

[dependencies]
half = "^2.1.0"
alsa = "^0.8.1"
configparser = { version = "^3.0.2", features=["indexmap"] }
clap = { version = "4.1.6", features=["derive"] }
log = "0.4.17"
clap-verbosity-flag = "2.0.0"
simple_logger = "4.0.0"
